// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RPG_ESI07.Infrastructure.Data;

#nullable disable

namespace RPG_ESI07.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EventData")
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AuditLogs", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_EventType", "\"EventType\" IN ('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', \r\n                    'DATA_EXPORT', 'DATA_DELETE', 'DATA_MODIFY', \r\n                    'CHEAT_DETECTED', 'ADMIN_ACTION', 'MFA_ENABLED', 'MFA_FAILED')");
                        });
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.BestiaryUnlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EnemyId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EnemyId");

                    b.HasIndex("PlayerId", "EnemyId")
                        .IsUnique();

                    b.ToTable("BestiaryUnlocks");
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.CombatStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CombatsLost")
                        .HasColumnType("integer");

                    b.Property<int>("CombatsWon")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCombats")
                        .HasColumnType("integer");

                    b.Property<long>("TotalDamageDealt")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDamageTaken")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalPlaytimeMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("CombatStats", t =>
                        {
                            t.HasCheckConstraint("CK_CombatStats_Positive", "\"CombatsWon\" >= 0 AND \"CombatsLost\" >= 0");

                            t.HasCheckConstraint("CK_CombatStats_Totals", "\"TotalCombats\" = \"CombatsWon\" + \"CombatsLost\"");
                        });
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("integer");

                    b.Property<int>("GoldReward")
                        .HasColumnType("integer");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer");

                    b.Property<float>("MagicalResistance")
                        .HasColumnType("real");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("PhysicalResistance")
                        .HasColumnType("real");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Enemies", t =>
                        {
                            t.HasCheckConstraint("CK_Enemy_Resistance", "\"PhysicalResistance\" BETWEEN 0.5 AND 2.0 AND \"MagicalResistance\" BETWEEN 0.5 AND 2.0");

                            t.HasCheckConstraint("CK_Enemy_Stats", "\"MaxHP\" > 0 AND \"Strength\" > 0");

                            t.HasCheckConstraint("CK_Enemy_Type", "\"Type\" IN ('basic', 'miniboss', 'boss')");
                        });
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.GameSave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InventoryData")
                        .HasColumnType("jsonb");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<float>("PositionX")
                        .HasColumnType("real");

                    b.Property<float>("PositionY")
                        .HasColumnType("real");

                    b.Property<string>("QuestFlags")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "SavedAt");

                    b.ToTable("GameSaves", t =>
                        {
                            t.HasCheckConstraint("CK_GameSave_Zone", "\"CurrentZone\" IN ('Tutorial', 'BossFinal')");
                        });
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EffectValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("StatModifiers")
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Items", t =>
                        {
                            t.HasCheckConstraint("CK_Item_Price", "\"Price\" >= 0");

                            t.HasCheckConstraint("CK_Item_Type", "\"Type\" IN ('weapon', 'armor', 'accessory', 'consumable')");
                        });
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.PlayerInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerId", "ItemId")
                        .IsUnique();

                    b.ToTable("PlayerInventory", t =>
                        {
                            t.HasCheckConstraint("CK_PlayerInventory_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.PlayerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentMP")
                        .HasColumnType("integer");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMP")
                        .HasColumnType("integer");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PlayerProfiles", t =>
                        {
                            t.HasCheckConstraint("CK_PlayerProfile_HP", "\"CurrentHP\" >= 0 AND \"CurrentHP\" <= \"MaxHP\"");

                            t.HasCheckConstraint("CK_PlayerProfile_Level", "\"Level\" >= 1 AND \"Level\" <= 99");

                            t.HasCheckConstraint("CK_PlayerProfile_MP", "\"CurrentMP\" >= 0 AND \"CurrentMP\" <= \"MaxMP\"");

                            t.HasCheckConstraint("CK_PlayerProfile_Stats", "\"Strength\" > 0 AND \"Intelligence\" > 0 AND \"Speed\" > 0");
                        });
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.PlayerSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("PlayerId", "SkillId")
                        .IsUnique();

                    b.ToTable("PlayerSkills");
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseDamage")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ElementType")
                        .HasColumnType("text");

                    b.Property<int?>("HealAmount")
                        .HasColumnType("integer");

                    b.Property<int>("MPCost")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills", t =>
                        {
                            t.HasCheckConstraint("CK_Skill_EffectType", "\"EffectType\" IN ('damage', 'heal', 'buff', 'debuff')");

                            t.HasCheckConstraint("CK_Skill_MPCost", "\"MPCost\" > 0");
                        });
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("text");

                    b.Property<byte[]>("Email")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastLoginIP")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("MfaSecret")
                        .HasColumnType("bytea");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.UserConsent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AnalyticsConsent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MarketingConsent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserConsents");
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("RPG_ESI07.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.BestiaryUnlock", b =>
                {
                    b.HasOne("RPG_ESI07.Domain.Entities.Enemy", "Enemy")
                        .WithMany("BestiaryUnlocks")
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPG_ESI07.Domain.Entities.PlayerProfile", "Player")
                        .WithMany("BestiaryUnlocks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enemy");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.CombatStats", b =>
                {
                    b.HasOne("RPG_ESI07.Domain.Entities.PlayerProfile", "Player")
                        .WithOne("CombatStats")
                        .HasForeignKey("RPG_ESI07.Domain.Entities.CombatStats", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.GameSave", b =>
                {
                    b.HasOne("RPG_ESI07.Domain.Entities.PlayerProfile", "Player")
                        .WithMany("GameSaves")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.PlayerInventory", b =>
                {
                    b.HasOne("RPG_ESI07.Domain.Entities.Item", "Item")
                        .WithMany("PlayerInventories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPG_ESI07.Domain.Entities.PlayerProfile", "Player")
                        .WithMany("Inventory")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.PlayerProfile", b =>
                {
                    b.HasOne("RPG_ESI07.Domain.Entities.User", "User")
                        .WithOne("PlayerProfile")
                        .HasForeignKey("RPG_ESI07.Domain.Entities.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.PlayerSkill", b =>
                {
                    b.HasOne("RPG_ESI07.Domain.Entities.PlayerProfile", "Player")
                        .WithMany("Skills")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPG_ESI07.Domain.Entities.Skill", "Skill")
                        .WithMany("PlayerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.UserConsent", b =>
                {
                    b.HasOne("RPG_ESI07.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.Enemy", b =>
                {
                    b.Navigation("BestiaryUnlocks");
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.Item", b =>
                {
                    b.Navigation("PlayerInventories");
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.PlayerProfile", b =>
                {
                    b.Navigation("BestiaryUnlocks");

                    b.Navigation("CombatStats");

                    b.Navigation("GameSaves");

                    b.Navigation("Inventory");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.Skill", b =>
                {
                    b.Navigation("PlayerSkills");
                });

            modelBuilder.Entity("RPG_ESI07.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("PlayerProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
