name: Backend CI

on:
  push:
    branches:
      - develop
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Requis pour une analyse précise de la version

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Restore
        run: dotnet restore RPG_ESI07.slnx

      - name: SonarQube Begin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"ThomasZadikian_rpg_esi07" \
            /o:"thomaszadikian" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.vstest.reportsPaths="**/*.trx" \
            /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"

      - name: Build
        run: dotnet build RPG_ESI07.slnx --no-restore --configuration Release

      - name: Test
        run: |
          dotnet test RPG_ESI07.slnx --no-build --configuration Release \
          /p:CollectCoverage=true \
          /p:Threshold=70 \
          /p:ThresholdType=line \
          /p:ThresholdStat=average \
          /p:CoverletOutputFormat=opencover \
          --collect:"XPlat Code Coverage"
      - name: SonarQube End
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"